### PR TITLE
adding forced redirect to .htaccess per issue/22

### PR DESCRIPTION
**Pull request by mikemadison13**

### CODE REVIEW

**Comment by aweingarten** [comment]
@mikemadison13 you did a pull instead of rebase here.  That's why you have these messy 
"@mikemadison13	Merge branch 'master' into issue22https" commits.  

Do a 
1: `git remote update` 
2: `git rebase -i` 
3: and delete those 2 commits/lines
4: Save the file

cc: @timwood this is why I don't like git pull!

**Comment by timwood** [comment]
I believe this time I also did a simple `git pull`. I don't really see the difference or issue. I suppose those "Merge branch..." commits are annoying, but I'm meh about it. I'll try to `git remote update && git rebase -i` for this project.

**Comment by aweingarten** [comment]
@timwood the merge commits are problematic because they start adding items to the PR that don't belong. They could inadvertently introduce unintended code  They make it hard to understand what exactly is happening in the PR. They also pollute the commit history.

**Comment by mikemadison13** [comment]
I'll redo it :)

----
Mike Madison
Technical Architect
mike.madison@acquia.com | (857) 301-8407

**Pull request closed without merging**
