### PR TITLE
DGC-477: Improve User Display

### PR DESCRIPTION
**Pull request by charlieartist**
Now, this a big addition.

It contains:

- Revised user profile display (fields added, content type template, custom icons).
- Revised Attendee display.
- Revised Organizer display.
- Revised Presenter display.

There are a lot of changes in here--I combined a number of tickets in to knock stuff out in one fell swoop. A number of new fields and a new image type are added.

### CODE REVIEW

**Comment by bheatonf1** [comment]
If we have time, we may want to make the text in the template a block rather than a lot of fixed code: https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/527/files#diff-aacad70e4a95f5c3a3f1be06a53caa04

**Comment by bheatonf1** [comment]
@charlieartist - a few things:
User picture is missing - variable should be 'content.field_picture'
Make field templates for all user fields

field--field-company.html.twig

hide the labels like so:

{% if multiple %}
    <div{{ attributes }}>
        {% for item in items %}
            <div{{ item.attributes }}>{{ item.content }}</div>
        {% endfor %}
    </div>
{% else %}
    {% for item in items %}
        <div{{ attributes }}>{{ item.content }}</div>
    {% endfor %}
{% endif %}

**Comment by charlieartist** [comment]
OK. If anyone is able to review, this should be good to go.

**Comment by mikemadison13** [comment]
closing in favor of https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/541 which should have the same commits, just without the bad merges

**Pull request closed without merging**
