### PR TITLE
[dgc-310] Add #states properties to ‘address’ city and state elements…

### PR DESCRIPTION
**Pull request by brooke-heaton**
@timwood I've been able to conditionally make State and City required if the use selects 'United States' as the Country option. Huzzah. This is probably fairly high priority.

### CODE REVIEW

**Comment by timwood** [comment]
Reviewing locally.

**Comment by bheatonf1** [comment]
@timwood will do. I'll wrap this up this evening.

**Comment by bheatonf1** [comment]
@timwood I think I've exhausted all avenues. It might be good to have someone else with strong Front End/Jquery experience take a look. I know the script is loaded when the form loads and it is loaded on validation failure, but for some reason it doesn't trigger right after the validation.

**Comment by mikemadison13** [comment]
the rebase on this PR is really messy @bheatonf1 given the changes that have been made elsewhere. what do we need to get this wrapped up?

**Comment by bheatonf1** [comment]
I will need to rebranch from stable and cherry pick these changes. I'm a bit lost on where there are at the moment - had hoped to have merged this in long long ago.

**Pull request closed without merging**
