### PR TITLE
Updated Proposed sessions.

### PR DESCRIPTION
**Pull request by lkopacz**

### CODE REVIEW

**Comment by mikemadison13** [comment]
@lkopacz this looks good mostly, but it could use some TLC with styling, as well as the missing "accepted sessions" view. can you just add a new display as part of this same ticket so we don't have to do that separately ?

**Comment by timwood** [comment]
@lkopacz Was there a reason you decided to link to the taxonomy term page from the "More [session track]" links rather than linking to a view display with the argument passed? We lose the whole look and feel in the full session track list by linking to the taxonomy term page.

Also, I recently noticed when talking to someone who is participating in the session review, that the full session node view doesn't include the author name or username or anything, unless they've added it to the body.

**Comment by jdearie** [comment]
How are the number of sessions per track determined? There doesn't appear to be consistency... some have 3 some have 5...

**Comment by timwood** [comment]
It's 5, but on Dev, some tracks have less than 5.

**Comment by jdearie** [comment]
@timwood - ah ok.  dev doesn't have all the sessions we have now... makes sense. thx!

**Pull request merged**
