### PR TITLE
SAT-1070: DDEV support plus removing BLT parts.

### LINKED ISSUE #1070: Add DDEV support.
https://docs.acquia.com/acquia-cms/add-ons/blt
Since BLT is going away, I could contribute the DDEV config and add the README instructions.
Let me know if there is interest in switching or supporting both Lando and DDEV.

Also, I noticed the number of active mantainer's has decreased in the last few years. I could do some front-end cleanup and general updates as part of adding the DDEV config.

I used the original lando config on previous job, it help a lot while trying to figure out how to work around certain issues.

### PR DESCRIPTION
**Pull request by bmartinez287**
The PR below was tested so a clean clone and install of the repo will create a project after ddev or lando start. Fixes #1070

### CODE REVIEW

**Comment by mikemadison13** [comment]
FYI @bmartinez287 it looks like some of the settings files you manipulated causes a break in the build. The pipelines script is failing due to inability to connect to the data. LMK if you need help.

**Comment by bmartinez287** [comment]
Oooo thanks for the feedback. I clicked on it but I couldn't see the error so I wasn't sure. I will try a few things first. If they don't work, I will reach out.

**Comment by mikemadison13** [comment]
@bmartinez287 do you have an acquia cloud account? slack me if you do and i'll add you to the project so you can see pipelines output.

**Comment by bmartinez287** [comment]
I tested this changes with DDEV version v1.23.1 and Lando v3.21.0

Screenshot 2024-06-06 at 1 26 57 PM

Screenshot 2024-06-06 at 1 57 29 PM


Lando has a slower build time likely due to mutagen. I pointed DDEV to the same node version but I got this error.
Screenshot 2024-06-06 at 2 12 14 PM
That said, the theme seems to compile. However, i haven't looked deep into that error.
All that said, we could probably do a follow-up PR to update the theme so it's not stuck on 14.

**Pull request merged**
