### PR TITLE
DGC-226 Style Internal Page Header

### PR DESCRIPTION
**Pull request by charlieartist**
Internal header component created, styled. In responsive layouts, this element should only display in the desktop/wide view, with the logo serving both as branding and as the home link. In tablet/mobile views, the home link is replaced by the GC17 wordmark in the left corner of the navbar.

For optimal bandwidth performance, the background image is a progressive JPEG, resulting in significant file-size savings.

### CODE REVIEW

**Comment by aweingarten** [comment]
Replaced by https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/228

**Comment by aweingarten** [comment]
@charlieartist will different internal pages get different backgrounds?  Or do they all get the same ?  I ask because depending on the answer we may need to build a slightly different custom block.

**Comment by charlieartist** [comment]
No--this is the generic internal page header.

**Comment by charlieartist** [comment]
Rebase borked. Closing this issue, will open another one.

**Pull request closed without merging**
