### PR TITLE
SAT-1078: Updates theme to dart scss and latest npm

### LINKED ISSUE #1078: Update theme to dart-scss

### PR DESCRIPTION
**Pull request by bmartinez287**
Screenshot 2024-06-08 at 1 02 25 AM
Screenshot 2024-06-08 at 12 59 12 AM

Tested on both Lando and DDEV.
closes #1078 

This moves us to node 20 and npm 10 plus it adds gulp 5.

### CODE REVIEW

**Comment by bmartinez287** [comment]
Aquia pipelines is pinned down at v16.20.2 because going higher creates an issue.
The current version of ubuntu they use is too old.
Screenshot 2024-06-08 at 1 49 36 AM
Screenshot 2024-06-08 at 1 49 46 AM
Any workaround so they can use the latest or should the pipeline build an older version?

**Comment by bmartinez287** [comment]
https://docs.acquia.com/acquia-cloud-platform/add-ons/node-js/start
image
I guess it can be updated in the UI and then on the pipelines script.

**Comment by mikemadison13** [comment]
@bmartinez287 i'll ask around re: node version. we really should have the same node version "all the places" and i see 16, 20, and 21 in various places in the PR. we should try to lock that down.

**Comment by bmartinez287** [comment]
Sounds good. If you could confirm or switch it to the latest node and npm versions that Aquia pipelines supports I will make it match that.

**Comment by mikemadison13** [comment]
@bmartinez287 what errors did you get on node 20? it should be supported in pipelines. see https://docs.acquia.com/acquia-cloud-platform/features/pipelines/known-issues#section-only-one-version-of-nodejs-18-and-20-is-supported-at-a-time

**Comment by bmartinez287** [comment]
This was the error. 
Screenshot 2024-06-08 at 1 49 36 AM
The version of ubuntu running on pipelines was missing those items.

**Comment by mikemadison13** [comment]
i think you need to bump NPM to version 10.x

**Comment by bmartinez287** [comment]
Maybe we do need to change the runtime version on the UI. I can't see that section but you should be able to switch it.
Screenshot 2024-06-10 at 11 37 07 AM
npm 10 does require a newer version of glib. The `ldd --version` seems to indicate that.

**Comment by bmartinez287** [comment]
@mikemadison13
Pipelines now runs using node v20.5.0 (npm v9.8.0)
DDEV uses npm v10.5.2 and node v20.13.1 which is the latest one and the default choice.
Lando uses https://deb.nodesource.com/setup_20.x which I assume installs the latest version of 20.

Is that ok? They are technically all 20. Or would you like them all to match pipelines on node and npm minor versions?

**Comment by mikemadison13** [comment]
ideally the npm versions would at least be the same major (10.x) if not the same minor as well.

**Comment by bmartinez287** [comment]
DDEV and Acquia are running on the same npm and node versions. (node v20.5.0 and npm v9.8.0)
Lando was trickier, it's on node v19.9.0 and npm v9.6.3. The closest it would go with nodesource. I try adding nvm but that had its own set of issues.

**Comment by bmartinez287** [comment]
With that last PR, all of 3 of them (Acquia pipeline, DDEV, and Lando) are running node v20.5.0 and npm v9.8.0.

**Pull request merged**
