### PR TITLE
DGC-000: webform spam mitigation update.

### PR DESCRIPTION
**Pull request by mikemadison13**

### CODE REVIEW

**Comment by timwood** [comment]
@mikemadison13 How do we know all those webform submissions are spam?

**Comment by mikemadison13** [comment]
@timwood so that's a good question... the first update are all 'not the United States' as the country, but have been entered with a US State or Territory. So those all seem suspect. The second update is a little more hand wavey, @jdearie and I have been talking on slack to try and pinpoint exactly what seems fake / what seems real. Open to thoughts if you have 'em!

**Comment by timwood** [comment]
Not sure what to recommend. Did @jdearie and you review the set of submissions this targets? I can review a third of those for validity if you all want.

**Comment by mikemadison13** [comment]
@timwood i'm really comfortable with the country/state script. I'm less clear on the secondary one (the country list). The end result is roughly ~700. @jdearie has gone through and manually cleared out spam a time or two and the numbers are pretty close to what she's doing vs. what the script is doing (although that certainly could be crossing some logical decisions that aren't correct).

**Comment by jdearie** [comment]
@timwood - i downloaded the submissions and checked every single one. I feel very confident that the ones we are removing are spam.  There were a few that were questionable and I left those in.

**Comment by timwood** [comment]
@jdearie You are awesome.

**Pull request merged**
