### PR TITLE
dgc-492: Update ‘My Schedule’ view to duplicate look/feel of Schedule…

### PR DESCRIPTION
**Pull request by bheatonf1**
Added Block Display to 'Schedule' view and removed filters/contextual filters and required user flagging

### CODE REVIEW

**Comment by bheatonf1** [comment]
@lkopacz if you have time

**Comment by alisonjo2786** [comment]
@bheatonf1 I'm seeing a bit of twig code on /user/login:

image

**Comment by alisonjo2786** [comment]
@bheatonf1 

It *looks* great.  But... The sorting is wacky -- I get the "Monday" heading at the top, and then it shows the list of sessions I added to my schedule, grouped by TIME, but not by date-THEN-time -- er, actually, it's not even quite that, b/c somehow Wednesday 9am sessions are further down below some Mon/Tues 1pm sessions... Anyway, screenshot attached.  *NOTE:* I added the session day/time to the teaser output just so it's extra clear for me (and you) what date/time is showing where.

dgc_ajm-my-schedule-screenshot 20170720

**Comment by bheatonf1** [comment]
Thanks so much @alisonjo2786 - this is why code review is so helpful Unfortunately this ticket may take MUCH longer to wrap up. The original 'Schedule' view contains a contextual filter for each day -which we can't really clone on the user/* pages. So, this view may need to be rebuilt entirely or we may need to scrap the idea of reusing the Schedule view. I'll take a look but don't have bandwidth this week.

**Pull request merged**
