### PR TITLE
DGC-169: Add video field to sessions content type.

### PR DESCRIPTION
**Pull request by phernand42**
DGC-169

### CODE REVIEW

**Comment by mikemadison13** [comment]
@phernand42 this just adds the storage for the field, there should be a couple of additional configuration files that add the field to the form for sessions and another for the various display modes for the session node type. i would expect at least 3-4 config files total.

**Comment by phernand42** [comment]
Sorry about that @mikemadison13 I'll get that corrected right now.

**Comment by phernand42** [comment]
Super sorry about that @mikemadison13 , should now be ready for review.

**Comment by mikemadison13** [comment]
this is ready to merge, pending a few questions on the ticket.

**Pull request merged**
