### PR TITLE
[dgc-310] Add provinces to working options list on Registration Addre…

### PR DESCRIPTION
**Pull request by bheatonf1**
Add provinces to working options list on Registration Address ‘state’ element, add options list config
Add alter to address subfield #weights and add jquery tiggle for .show/.hide on State and City fields

### CODE REVIEW

**Comment by timwood** [comment]
@bheatonf1 I think @lkopacz added the provinces in #344

**Comment by timwood** [comment]
That Travis guy is a real stickler.

**Comment by bheatonf1** [comment]
Hehe, yea. Give a guy a break, Travis.

**Comment by bheatonf1** [comment]
hm, yea @timwood conditionals and #states don't seem to play well with subfields in forms. I had sworn this was working well at some point and can't pinpoint the issue. I may need to just try jquery from the front end, though I'd rather not.

**Pull request merged**
